

development:
  adapter: postgresql
  encoding: unicode
  database: planet_express_development
  pool: 5
  username: fredericomorato
  password:
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: planet_express_test
  pool: 5
  username: fredericomorato
  password:
  timeout: 5000
